- name: Create the images directory
  file:
    path: /home/stack/images/
    state: directory

- name: Download the images
  get_url:
    url: "{{ item }}"
    dest: /home/stack/images/
  loop:
    - "https://images.rdoproject.org/{{ openstack_release }}/rdo_trunk/current-tripleo-rdo/ironic-python-agent.tar"
    - "https://images.rdoproject.org/{{ openstack_release }}/rdo_trunk/current-tripleo-rdo/overcloud-full.tar"

- name: Extract the images
  unarchive:
    src: "/home/stack/images/{{ item }}"
    dest: /home/stack/images/
    remote_src: true
  loop:
    - ironic-python-agent.tar
    - overcloud-full.tar

- name: Upload the image to Glance
  shell: . /home/stack/stackrc && openstack overcloud image upload --image-path /home/stack/images/
